# Generated by Django 5.2.5 on 2025-11-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_userfreeusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfreeusage',
            name='total_used_ai',
        ),
        migrations.RemoveField(
            model_name='userfreeusage',
            name='total_used_places',
        ),
        migrations.RemoveField(
            model_name='userfreeusage',
            name='total_used_weather',
        ),
    ]
