# Generated by Django 5.2.7 on 2025-10-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(max_length=255),
        ),
    ]
