# Generated by Django 5.2.7 on 2025-10-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_activity_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='place',
            new_name='place_id',
        ),
    ]
