# Generated by Django 5.2.5 on 2025-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_activity_latitude_activity_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('saved', 'Saved'), ('recent', 'Recent'), ('reservation', 'Reservation'), ('saved-delete', 'Saved Delete'), ('recent-delete', 'Recent Delete'), ('reservation-delete', 'Reservation Delete')], max_length=20, null=True),
        ),
    ]
