# Generated by Django 5.2.5 on 2025-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Saved', 'verbose_name_plural': 'Saved'},
        ),
        migrations.AddField(
            model_name='activity',
            name='directions_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_currency',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
