# Generated by Django 5.2.5 on 2025-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_alter_activity_options_activity_directions_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
