# Generated by Django 5.2.7 on 2025-10-12 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('PROBLEM', 'problem'), ('REPORT', 'report'), ('FEEDBACK', 'feedback')], max_length=50)),
                ('problem', models.TextField(blank=True, default='', null=True)),
                ('report', models.TextField(blank=True, default='', null=True)),
                ('feedback', models.TextField(blank=True, default='', null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Send', 'send'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='Send', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
