# Generated by Django 5.2.5 on 2025-12-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('support.support',),
        ),
        migrations.CreateModel(
            name='SupportProblem',
            fields=[
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('support.support',),
        ),
        migrations.CreateModel(
            name='SupportReport',
            fields=[
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('support.support',),
        ),
    ]
