# Generated by Django 5.2.7 on 2025-10-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('best_reason', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('place_type', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(blank=True, default=0)),
                ('review', models.FloatField(blank=True, default=0)),
                ('distance_km', models.FloatField(blank=True)),
                ('distance_time', models.CharField(blank=True)),
                ('directions_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('price_currency', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
